Logout and delete update: * backend: for the patient update required file were changed and checked in the postman * frontend:     1. add appoinment code added but not worked     2. delete appointment done     3. fetch all appointments: minor bug, if the logged in patient does not have any appointments only the no appointments card appera     4. login: usercontext altered for the component data altering     5. centre: logout button added and worked successfully     6. update patient details: added code but not worked
ERROR: add and update aappointments, update patient details